<%@ Page Title="" Language="C#" MasterPageFile="~/Cobro/MPCobro.master" AutoEventWireup="true" CodeBehind="Cobros.aspx.cs" Inherits="WebCABDN.Cobro.Cobros" %>
<asp:Content ID="Content1" ContentPlaceHolderID="contenidoPrincipal" runat="server">

    <h2>Administración de datos cobros</h2>

    <p>
        <asp:Label ID="lblError" runat="server"></asp:Label>
    </p>

    <p>
    <asp:ImageButton ID="ibNewCobro" runat="server" ImageUrl="~/images/AddCobro64.png" OnClick="ibNewCobro_Click" />
    </p>

    <p>
    <asp:GridView ID="gvCobros" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnRowCancelingEdit="gvCobros_RowCancelingEdit" OnRowCommand="gvCobros_RowCommand" OnRowDeleting="gvCobros_RowDeleting" OnRowEditing="gvCobros_RowEditing" OnRowUpdating="gvCobros_RowUpdating">
        <AlternatingRowStyle BackColor="White" />
        <EditRowStyle BackColor="#7C6F57" />
        <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#E3EAEB" />
        <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#F8FAFA" />
        <SortedAscendingHeaderStyle BackColor="#246B61" />
        <SortedDescendingCellStyle BackColor="#D4DFE1" />
        <SortedDescendingHeaderStyle BackColor="#15524A" />
    </asp:GridView>
    </p>

</asp:Content>
