<%@ Page Title="" Language="C#" MasterPageFile="~/Socio/MPSocio.master" AutoEventWireup="true" CodeBehind="Socio.aspx.cs" Inherits="WebCABDN.Socio.Socio" %>
<asp:Content ID="Content1" ContentPlaceHolderID="contenidoPrincipal" runat="server">
        <h2>Administración de socios</h2>
    <p>
        <asp:Label ID="lblError" runat="server"></asp:Label>
    </p>
<p>
    <asp:ImageButton ID="ibNewSocio" runat="server" ImageUrl="~/images/AddSocio64.png" OnClick="ibNewSocio_Click" />
&nbsp;&nbsp;&nbsp;<asp:ImageButton ID="ImageButton1" runat="server" ImageUrl="~/images/Printer-64.png" OnClick="ImageButton1_Click" />
    &nbsp;&nbsp;&nbsp;&nbsp; Filtrar x:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:DropDownList ID="cbFiltro" runat="server">
    </asp:DropDownList>
&nbsp;&nbsp;&nbsp;
    <asp:TextBox ID="tbFiltro" runat="server"></asp:TextBox>
&nbsp;
    <asp:ImageButton ID="ibBuscar" runat="server" ImageUrl="~/images/Search-48x48.png" OnClick="ibBuscar_Click" />
</p>
<p>
    <asp:GridView ID="gvSocios" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnRowCancelingEdit="gvSocios_RowCancelingEdit" OnRowCommand="gvSocios_RowCommand" OnRowDeleting="gvSocios_RowDeleting" OnRowEditing="gvSocios_RowEditing" OnRowUpdating="gvSocios_RowUpdating">
        <AlternatingRowStyle BackColor="White" />
        <EditRowStyle BackColor="#7C6F57" />
        <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#E3EAEB" />
        <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#F8FAFA" />
        <SortedAscendingHeaderStyle BackColor="#246B61" />
        <SortedDescendingCellStyle BackColor="#D4DFE1" />
        <SortedDescendingHeaderStyle BackColor="#15524A" />
    </asp:GridView>
</p>

</asp:Content>
